branch-defaults:
  master:
    environment: bpho-production
environment-defaults:
  bpho-production:
    branch: null
    repository: null
global:
  application_name: bpho
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Docker running on
    64bit Amazon Linux/2.7.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: peroshi
  sc: git
  workspace_type: Application
